CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS taches (
   idTache INT AUTO_INCREMENT PRIMARY KEY,
   idImportance INT NOT NULL, 
   nomTache VARCHAR(50) NOT NULL, 
   descriptionTache VARCHAR(100) NOT NULL
);


